databases:
  - name: tracker-db
    plan: free
    databaseName: tracker
    user: tracker

services:
  - type: web
    name: enerxon-china-tracker
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: tracker-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.11.0
